version: '3.8'
services:
  app:
    build: .
    container_name: praktisi_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - .env # Pastikan file .env tersedia di direktori proyek sebelum menjalankan container
    ports:
      - "8000:8000"
    networks:
      - praktisi_network

  db:
    image: mysql:8
    container_name: praktisi_db
    restart: always
    environment:
      MYSQL_DATABASE: praktisi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306" # Untuk akses dari luar container jika dibutuhkan
    networks:
      - praktisi_network

volumes:
  dbdata:
