version: '3.8'

services:
  app:
    build: .
    container_name: praktisi_app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - praktisi_network

  db:
    image: mysql:8
    container_name: praktisi_db
    restart: always
    environment:
      MYSQL_DATABASE: praktisi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - praktisi_network

volumes:
  dbdata:

networks:
  praktisi_network:
